# Generated by Django 5.0.6 on 2024-06-02 15:36

from django.db import migrations
# def insert (apps, schema_editor):
#    Measurement = apps.get_model('shop','Measurement')
#    Measurement.objects.create(waist='20',height='147',hips='35')

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_measurements_measurement_bust'),
    ]

    operations = [
        # migrations.RunPython(insert),
    ]
