# Generated by Django 5.0.6 on 2024-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240602_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='height',
            field=models.JSONField(default=147),
        ),
        migrations.AddField(
            model_name='measurement',
            name='hips',
            field=models.JSONField(default=32),
        ),
        migrations.AddField(
            model_name='measurement',
            name='waist',
            field=models.JSONField(default=14),
        ),
    ]
